name: Deploy Site

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  

      - name: Instalar dependências
        run: npm install

      - name: Rodar o build (com CI=false)
        run: CI=false npm run build  # Desabilita warnings sendo tratados como erros

      - name: Rodar o deploy
        run: npm run deploy
